// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkerAPI.Models;

#nullable disable

namespace WorkerAPI.Migrations
{
    [DbContext(typeof(WorkerDetailContext))]
    partial class WorkerDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkerAPI.Models.WorkerDetail", b =>
                {
                    b.Property<int>("WorkerDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerDetailId"));

                    b.Property<DateOnly>("Workerbirthday")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Workerfirstame")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkerlastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly>("stardate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.HasKey("WorkerDetailId");

                    b.ToTable("PaymentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
